- name: install haproxy
  package:
    name: haproxy
    state: present

- name: populate service facts
  service_facts:

- name: Set selinux haproxy flag on and keep them persistent across reboots
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes
  when: ansible_selinux.status == "enabled"

- name: ensure haproxy is running
  service:
    name: haproxy
    state: started
    enabled: yes

- name: configure haproxy.cfg from template
  template:
    src: "{{ playbook_dir }}/../templates/haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
  notify:
    - restart haproxy

- name: Allow infrastructure services on firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public
  loop:
    - http
    - https
  when: ansible_facts.services['firewalld.service'].status == 'enabled'

- name: Open ports for infrastructure services on firewall
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public
  loop:
    - "5555/tcp"
    - "22623/tcp"
    - "6443/tcp"
  when: ansible_facts.services['firewalld.service'].status == 'enabled'

