- name: restart dhcpd
  service:
    name: dhcpd
    state: restarted

- name: restart named
  service:
    name: named
    state: restarted

- name: restart haproxy
  service:
    name: haproxy
    state: restarted

