- name: Add disks to virtual machine
  vmware_guest_disk:
    hostname: "{{ vcenter.hostname }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter }}"
    validate_certs: no
    folder: "{{ vcenter.folder }}"
    name: "{{ item }}"
    disk: "{{ additional_disks }}"
#    - size_mb: "{{ additional_disk_size }}"
#      type: thin
#      datastore: "{{ vcenter.datastore }}"
#      state: present
#      scsi_controller: 1
#      unit_number: 1
#      scsi_type: 'paravirtual'
  loop: "{{ nodes }}"
  delegate_to: localhost
