- name: Create OCP node with DHCP
  vmware_guest:
    hostname: "{{ vcenter.hostname }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter }}"
    cluster: "{{ vcenter.cluster }}"
    validate_certs: no
    folder: "/{{ vcenter.datacenter }}/vm/{{ cluster_name }}"
    name: "{{ item.name }}"
    state: poweredoff
    template: "{{ ova_template_name }}"
    disk:
    - size_gb: "{{ item.disk }}"
      type: thin
      datastore: "{{ vcenter.datastore }}"
    hardware:
      memory_mb: "{{ item.memory }}"
      num_cpus: "{{ item.cpu }}"
      memory_reservation_lock: True
      mem_limit: "{{ item.memory }}"
      mem_reservation: "{{ item.memory }}"
      hotadd_cpu: True
      hotremove_cpu: True
      hotadd_memory: False
    customvalues:
      - key: "disk.EnableUUID"
        value: "TRUE"
      - key: "guestinfo.ignition.config.data.encoding"
        value: "base64"
      - key: "guestinfo.ignition.config.data"
        value: "{{ ignition_payload }}"
    networks:
    - name: "{{ vcenter.network }}"
    wait_for_ip_address: no
  loop: "{{ nodes }}"
  delegate_to: localhost
  tags: vmware
  when: not static_ip

- name: Configure OCP node MAC address for DHCP
  vmware_guest_network:
    hostname: "{{ vcenter.hostname }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter }}"
    cluster: "{{ vcenter.cluster }}"
    validate_certs: no
    folder: "/{{ vcenter.datacenter }}/vm/{{ cluster_name }}"
    name: "{{ item.name }}"
    gather_network_info: false
    networks:
    - name: "{{ vcenter.network }}"
      label: "Network adapter 1"
      state: present
      manual_mac: "{{ item.mac }}"
## This value is required if multiple distributed portgroups exists.
#      dvswitch_name: "{{ vcenter.dvswitch_name }}"
  loop: "{{ nodes }}"
  delegate_to: localhost
  tags: vmware
  when: not static_ip

- name: Create OCP node with static IP
  vmware_guest:
    hostname: "{{ vcenter.hostname }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter }}"
    cluster: "{{ vcenter.cluster }}"
    validate_certs: no
    folder: "/{{ vcenter.datacenter }}/vm/{{ cluster_name }}"
    name: "{{ item.name }}"
    state: poweredoff
    template: "{{ ova_template_name }}"
    disk:
    - size_gb: "{{ item.disk }}"
      type: thin
      datastore: "{{ vcenter.datastore }}"
    hardware:
      memory_mb: "{{ item.memory }}"
      num_cpus: "{{ item.cpu }}"
      memory_reservation_lock: True
      mem_limit: "{{ item.memory }}"
      mem_reservation: "{{ item.memory }}"
      hotadd_cpu: True
      hotremove_cpu: True
      hotadd_memory: False
    networks:
    - name: "{{ vcenter.network }}"
    customvalues:
      - key: "disk.EnableUUID"
        value: "TRUE"
      - key: "guestinfo.ignition.config.data.encoding"
        value: "base64"
      - key: "guestinfo.ignition.config.data"
        value: "{{ ignition_payload }}"
      - key: "guestinfo.afterburn.initrd.network-kargs"
        value: "ip={{ item.ip }}::{{ default_gw }}:{{ netmask }}:::none nameserver={{ nameserver }}"
    wait_for_ip_address: no
  loop: "{{ nodes }}"
  delegate_to: localhost
  tags: vmware
  when: static_ip

