- name: install httpd server to host ignition
  package:
    name: httpd
    state: present

- name: listen on port {{ httpd_port }}
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^(Listen) 80$'
    replace: '\1 {{ httpd_port }}'

- name: restart httpd server
  service:
    name: httpd
    state: restarted
    enabled: yes

- name: Copy install-config.yaml file
  copy:
    src: "{{ work_dir }}/bootstrap.ign"
    dest: "{{ document_root }}/bootstrap.ign"
    force: yes

