- name: Verify if install-config already run
  stat:
    path: "{{ work_dir }}/master.ign"
  register: manifest_ign
  tags: create_manifest

- name: unset mastersSchedulable
  replace:
    path: "{{ work_dir }}/manifests/cluster-scheduler-02-config.yml"
    regexp: '(mastersSchedulable:) true'
    replace: '\1 false'
  when: manifest_ign.stat.exists == false
  tags: create_manifest

- name: Remove manifest that define control plane machines and compute machineSets
  file:
    path: "{{ work_dir}}/{{ item }}"
    state: absent
  loop:
    - openshift/99_openshift-cluster-api_master-machines-0.yaml
    - openshift/99_openshift-cluster-api_master-machines-1.yaml
    - openshift/99_openshift-cluster-api_master-machines-2.yaml
    - openshift/99_openshift-cluster-api_worker-machineset-0.yaml
  when: manifest_ign.stat.exists == false
  tags: create_manifest

- name: create ignition-configs
  shell:
    cmd: /tmp/openshift-install create ignition-configs --dir={{ work_dir}}
    chdir: "{{ work_dir }}"
  when: manifest_ign.stat.exists == false

- name: install package to run base64 command
  package:
    name: coreutils
    state: present

- name: convert ignition to base64
  shell:
    cmd: base64 -w0 {{ work_dir }}/{{item}}.ign > {{ work_dir }}/{{item}}.64
  loop:
    - master
    - worker
    - bootstrap
  when: manifest_ign.stat.exists == false
  tags: replaceign

- name: Change permissions on generated files
  file:
    path: "{{ work_dir}}/{{ item }}"
    mode: '0644'
  loop:
    - master.ign
    - worker.ign
    - bootstrap.ign
    - metadata.json
  when: manifest_ign.stat.exists == false

- name: create ocp4-vars-dynamic.yaml empty var file
  template:
    src: "{{ playbook_dir }}/../templates/ocp4-vars-dynamic.yaml.j2"
    dest: "{{ playbook_dir }}/../vars/ocp4-vars-dynamic.yaml"
  tags: replaceign

- name: replace ignition payload in vars file
  replace:
    path: "{{ playbook_dir }}/../vars/ocp4-vars-dynamic.yaml"
    regexp: '^({{ placeholder }}).*$'
    replace: '\1: "{{ contents }}"'
  vars:
    contents: "{{ lookup('file', '{{ work_dir }}/{{ item }}') }}"
    placeholder: "{{ item | regex_replace('-', '_') | regex_replace('.64', '_ign') }}"
  loop:
    - bootstrap.64
    - master.64
    - worker.64
  tags: replaceign

