- name: check DNS record
  command: dig +short {{ record }}.{{ cluster_name }}.{{ base_domain }}
  register: result

- debug:
    msg: DNS query {{ record }}.{{ cluster_name }}.{{ base_domain }} --> {{ result.stdout }}

- assert:
    that:
      - result.stdout is regex("[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+")

