---
- name: Play to enable epel repo
  hosts: localhost
  become: yes

  tasks:
    - name: Assert that we are running on RedHat family system
      assert:
        that:
          - "ansible_os_family == 'RedHat'"

    - name: Install EPEL repo.
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present

    - name: Import EPEL GPG key.
      rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        state: present
