---
- name: Play to provision Infrastructure Services needed for OCP4 UPI installation
  hosts: localhost
  become: yes

  vars_files:
    - "{{ playbook_dir }}/../vars/ocp4-vars-vmware-upi-installer.yaml"

  tasks:
    - name: Assert that we are running on RedHat family system
      assert:
        that:
          - "ansible_os_family == 'RedHat'"

    - name: include task for 
      include_tasks: "{{ playbook_dir }}/../tasks/infrastructure-services-dhcp.yaml"

    - name: include task for 
      include_tasks: "{{ playbook_dir }}/../tasks/infrastructure-services-named.yaml"

    - name: include task for 
      include_tasks: "{{ playbook_dir }}/../tasks/infrastructure-services-haproxy.yaml"

  handlers:
    - import_tasks: "{{ playbook_dir }}/../tasks/infrastructure-services-handlers.yaml"
