---
- name: Test DNS records for OCP4
  hosts:
    - localhost
  gather_facts: no
  become: yes

  vars_files:
    - "{{ playbook_dir }}/../vars/ocp4-vars-vmware-upi-installer.yaml"

  tasks:
    - name: install dns and network utils
      package:
        name: "{{ item }}"
        state: present
      loop:
        - bind-utils
        - net-tools
        - telnet
        - curl
        - wget

    - name: include task to test VIP records
      include_tasks: "{{ playbook_dir }}/../tasks/ocp4-test-dns-VIPS.yaml"
      vars:
        record: "{{ item }}"
      loop:
        - api
        - api-int
        - "*.apps"

    - name: check SRV record
      command: dig _etcd-server-ssl._tcp.{{ cluster_name }}.{{ base_domain }} SRV +short
      register: result
    - debug:
        msg: DNS query _etcd-server-ssl._tcp.{{ cluster_name }}.{{ base_domain }} --> {{ result.stdout }}
    - assert:
        that:
          - "'0 10 2380 {{ etcdx }}.{{ cluster_name }}.{{ base_domain }}.' in result.stdout"
      loop:
        - etcd-0
        - etcd-1
        - etcd-2
      loop_control:
        loop_var: etcdx

    - name: test masters and etcd records consistency
      include_tasks: "{{ playbook_dir }}/../tasks/ocp4-test-dns-masters-etcd.yaml"
      vars:
        prefix: "{{ item }}"
      loop:
        - etcd-0
        - etcd-1
        - etcd-2

    - name: test bootstrap
      include_tasks: "{{ playbook_dir }}/../tasks/ocp4-test-dns-nodes.yaml"
      vars:
        addr: "{{ item.ip }}"
      loop: "{{ bootstrap }}"
      tags: ocp4-test-dns-nodes

    - name: test masters
      include_tasks: "{{ playbook_dir }}/../tasks/ocp4-test-dns-nodes.yaml"
      vars:
        addr: "{{ item.ip }}"
      loop: "{{ masters }}"
      tags: ocp4-test-dns-nodes

    - name: test workers
      include_tasks: "{{ playbook_dir }}/../tasks/ocp4-test-dns-nodes.yaml"
      vars:
        addr: "{{ item.ip }}"
      loop: "{{ workers }}"
      tags: ocp4-test-dns-nodes

