---
- name: Play to provision OCP4 cluster 2
  hosts: localhost
  become: yes

  vars_files:
    - "{{ playbook_dir }}/../vars/ocp4-vars-vmware-upi-installer.yaml"

  tasks:
    - name: include task vms for ignition config
      include_tasks: "{{ playbook_dir }}/../tasks/ocp4-ignition-config-2.yaml"
      tags: [ replaceign, create_manifest ]

    - name: Include vars for ignition files
      include_vars:
        file: "{{ playbook_dir }}/../vars/ocp4-vars-dynamic.yaml"
      tags: vmware

    - name: include create task vms for bootstrap node
      include_tasks: "{{ playbook_dir }}/../tasks/ocp4-nodes-create.yaml"
      vars:
        nodes: "{{ bootstrap }}"
        ignition_payload: "{{ bootstrap_ign }}"
        default_gw: "{{ machineCIDR_default_gw }}"
        netmask: "{{ machineCIDR_netmask }}"
        nameservers: "{{ machineDNS }}"
      tags: vmware
      when: bootstrap is defined

    - name: include create task vms for masters node
      include_tasks: "{{ playbook_dir }}/../tasks/ocp4-nodes-create.yaml"
      vars:
        nodes: "{{ masters }}"
        ignition_payload: "{{ master_ign }}"
        default_gw: "{{ machineCIDR_default_gw }}"
        netmask: "{{ machineCIDR_netmask }}"
        nameservers: "{{ machineDNS }}"
      tags: vmware
      when: masters is defined

    - name: include create task vms for workers node
      include_tasks: "{{ playbook_dir }}/../tasks/ocp4-nodes-create.yaml"
      vars:
        nodes: "{{ workers }}"
        ignition_payload: "{{ worker_ign }}"
        default_gw: "{{ machineCIDR_default_gw }}"
        netmask: "{{ machineCIDR_netmask }}"
        nameservers: "{{ machineDNS }}"
      tags: vmware
      when: workers is defined

