---
- name: Play to test required URI connection
  hosts: localhost
  gather_facts: no

  vars_files:
    - "{{ playbook_dir }}/../vars/ocp4-vars-proxy-whitelist.yaml"
    - "{{ playbook_dir }}/../vars/ocp4-vars-vmware-upi-installer.yaml"

  tasks:
    - name: Check that MANDATORY URI connect (GET) returns a status 200
      uri:
        url: "https://{{ item }}"
        timeout: 5
        validate_certs: no
        force: yes
      environment: "{{ proxy_env }}"
      loop:
        "{{ proxy_whitelist_mandatory }}"

