---
- name: Test DNS records for OCP4
  hosts:
    - localhost
  gather_facts: no
  become: yes

  vars_files:
    - "{{ playbook_dir }}/../vars/ocp4-vars-vmware-upi-installer.yaml"

  tasks:
    - name: install dns and network utils
      package:
        name: "{{ item }}"
        state: present
      loop:
        - bind-utils
        - net-tools
        - telnet
        - curl
        - wget

    - name: include task to test VIP records
      include_tasks: "{{ playbook_dir }}/../tasks/ocp4-test-dns-VIPS.yaml"
      vars:
        record: "{{ item }}"
      loop:
        - api
        - api-int
        - "*.apps"

    - name: test bootstrap
      include_tasks: "{{ playbook_dir }}/../tasks/ocp4-test-dns-nodes.yaml"
      vars:
        addr: "{{ item.ip }}"
      loop: "{{ bootstrap }}"
      tags: ocp4-test-dns-nodes

    - name: test masters
      include_tasks: "{{ playbook_dir }}/../tasks/ocp4-test-dns-nodes.yaml"
      vars:
        addr: "{{ item.ip }}"
      loop: "{{ masters }}"
      tags: ocp4-test-dns-nodes

    - name: test workers
      include_tasks: "{{ playbook_dir }}/../tasks/ocp4-test-dns-nodes.yaml"
      vars:
        addr: "{{ item.ip }}"
      loop: "{{ workers }}"
      tags: ocp4-test-dns-nodes

