---
- name: Play to poweron VMs of OCP cluster
  hosts: localhost
  gather_facts: no
  vars_files:
    - "{{ playbook_dir }}/../vars/ocp4-vars-vmware-upi-installer.yaml"

  tasks:

    - name: include poweron task vms for bootstrap node
      include_tasks: "{{ playbook_dir }}/../tasks/ocp4-nodes-poweron.yaml"
      vars:
        nodes: "{{ bootstrap }}"
      tags: skip
      when: bootstrap is defined

    - name: include poweron task vms for masters node
      include_tasks: "{{ playbook_dir }}/../tasks/ocp4-nodes-poweron.yaml"
      vars:
        nodes: "{{ masters }}"
      tags: skip
      when: masters is defined

    - name: include poweron task vms for workers node
      include_tasks: "{{ playbook_dir }}/../tasks/ocp4-nodes-poweron.yaml"
      vars:
        nodes: "{{ workers }}"
      when: workers is defined
